# Generated by Django 3.1.5 on 2021-01-16 18:35

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='description')),
                ('keywords', models.CharField(max_length=100, verbose_name='Keyword')),
                ('feed', models.URLField(blank=True, verbose_name='Custom Feed URL')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='Youtube')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('site', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('meta_key', models.CharField(max_length=50, verbose_name='Meta Key')),
                ('meta_value', models.TextField(verbose_name='Meta Value')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=256, verbose_name='URL')),
                ('guid', models.FileField(upload_to=core.utils.upload_location, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('a', 'audio'), ('d', 'document'), ('i', 'image'), ('v', 'video'), ('x', 'other')], default='x', max_length=1)),
                ('data', models.TextField(blank=True, null=True, verbose_name='Data')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
