# Generated by Django 3.1.5 on 2021-01-17 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=256, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated on')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published'), ('trash', 'Trash')], default='publish', help_text='With Draft chosen, will only be shown for admin users on the site.', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text="With Published chosen, won't be shown until this time", null=True, verbose_name='Published from')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, help_text="With Expired chosen, won't be shown after this time", null=True, verbose_name='Expires At')),
                ('featured_at', models.DateTimeField(blank=True, db_index=True, help_text='With Featured chosen, will set featured from this time', null=True, verbose_name='Featured at')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content body')),
                ('excerpt', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Excerpt')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='page_page_created_related', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('featured_image', models.ForeignKey(blank=True, db_column='object_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.attachment', verbose_name='featured_image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.page', verbose_name='Parent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_page_updated_related', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
